#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: Service
metadata:
  name: org1peer1couchdb
spec:
  selector:
    app: org1peer1couchdb
  ports:
  - name: couchport
    port: 5984
    targetPort: 5984
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org1peer1couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org1peer1couchdb
  template:
    metadata:
      labels:
        app: org1peer1couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb:3
        imagePullPolicy: IfNotPresent
        env:
          - name: "COUCHDB_USER"
            value: "admin" 
          - name: "COUCHDB_PASSWORD"
            value: "adminpw"
        ports:
            - containerPort: 5984